Vagrant.configure("2") do |config|
  
   #Creating VM1 
  config.vm.define "vm1" do |vm1|
    vm1.vm.box = 'centos/7'
    vm1.vm.network "forwarded_port", guest: 80, host: 7070

   #Inline Shell Provision
   vm1.vm.provision "shell",
   inline: "sudo yum update -y;"

  end

  #Creating VM2 
   config.vm.define "vm2" do |vm2|
    vm2.vm.box = "ubuntu/bionic64"
    vm2.vm.network "forwarded_port", guest: 80, host: 8080

    #Inline Shell Provisioning
    vm2.vm.provision :shell, :path => "script.sh"
	  
  end
end